---
- name: Establishing a FTP server on debian
  apt:
   name: vsftpd
   state: latest
   update_cache: yes

- name: Start FTP service
  service:
   name: vsftpd
   state: started
   enabled: yes

- name: Generate a ftp user
  user:
   name: '{{ user }}'
   password: '{{ ftp_pass }}'

- name: Denied user to access ssh
  lineinfile:
   path: /etc/ssh/sshd_config
   line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: Restarting sshd service
  service:
   name: sshd
   state: restarted
  when: successfully_denied.changed

- name: Copy the default configuration file
  copy:
   src: /etc/vsftpd.conf
   dest: /etc/vsftpd.conf.orig
   remote_src: True

- name: Limiting the users of ftp to own home directory
  replace:
   path: /etc/vsftpd.conf
   regexp: '#chroot_local_user=YES'
   replace: 'chroot_local_user=YES'

- name: Setup the  ftp file
  lineinfile:
   path: /etc/vsftpd.conf
   line: '{{ debianvar }}'

- name: Restart Vsftpd
  service:
   name: vsftpd
   state: restarted
# tasks file for roles/ftpdebian