---
# tasks file for roles/rolesubuntu
#Elasticsearch
- name: Downloading java
  apt:
   name: openjdk-11-jdk
   update_cache: yes

- name: Generating the ELK public GPG key
  apt_key:
   url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   state: present

- name: Making ELK source list is accessible
  lineinfile:
   path: /etc/apt/sources.list.d/elastic-7.x.list
   line: '{{ elasticsource }}'
   create: yes

- name: Downloading Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

- name: Editing cluster name
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name: my-application'
   replace: 'cluster.name: my-application'

- name: Editing node
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#node.name: node-1'
   replace: 'node.name: node-1'

- name: Editing network host
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#network.host: 192.168.0.1'
   replace: '{{ elasticnetwork }}'

- name: Editing port
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#http.port: 9200'
   replace: 'http.port: 9200'

- name: Service startup timeout setup
  lineinfile:
   path: /etc/systemd/system/elasticsearch.service.d/startup-timeout.conf
   line: '{{ elastictimeout }}'
   create: yes
  register: timeout

- name: Restarting services manager
  systemd:
   daemon_reload: yes
  when: timeout.changed

- name: Starting Elasticsearch Service
  service:
   name: elasticsearch
   enabled: yes
   state: started

#Kibana
- name: Downloading Dependency for Kibana
  apt:
   name: nginx
   update_cache: yes

- name: Downloading Kibana
  apt:
   name: kibana
   update_cache: yes

- name: Start kibana service
  systemd:
   name: kibana
   enabled: yes
   state: started

- name: Downloading pip for htpasswd
  apt:
   name: python3-pip
   state: latest
   update_cache: yes

- name: Making sure htpasswd module is present
  pip:
   name: passlib
   state: latest

- name: Creating Admin User
  htpasswd:
   path: /etc/nginx/htpasswd.users
   name: kibanaadmin
   password: '{{ kibanapass }}'

- name: Creating Nginx Virtual Host Configuration file
  copy:
   src: others/kibana
   dest: /etc/nginx/sites-available

- name: Creating hard link for kibana
  file:
   src: /etc/nginx/sites-available/kibana
   dest: /etc/nginx/sites-enabled/kibana
   remote_src: 'yes'
   state: link

- name: Restart nginx service
  service:
   name: nginx
   state: restarted

#Logstash
- name: Downloading Logstash
  apt:
   name: logstash
   update_cache: yes

- name: Downloading Filebeat
  apt:
   name: filebeat
   update_cache: yes

- name: Generating the 1st configuration file
  copy:
   src: others/02-beats-input.conf
   dest: /etc/logstash/conf.d

- name: Generating the 2nd configuration file
  copy:
   src: others/10-syslog-filter.conf
   dest: /etc/logstash/conf.d

- name: Generating the 3rd configuration file
  copy:
   src: others/30-elasticsearch-output.conf
   dest:  /etc/logstash/conf.d

- name: Starting Logstash
  service:
   name: logstash
   state: started
   enabled:

- name: Editing Filebeat Configuration PART1
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: 'output.elasticsearch:'
   replace: '#output.elasticsearch:'

- name: Editing Filebeat Configuration PART2
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: 'hosts:'
   replace: '#hosts:'
   after: 'output.elasticsearch:'
   before: 'Protocol - either'

- name: Editing Filebeat Configuration PART3
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: '#output.logstash:'
   replace: 'output.logstash:'

- name: Editing Filebeat Configuration PART4
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: '#hosts:'
   replace: 'hosts:'
   after: 'output.logstash:'
   before: ' Optional SSL.'

- name: Enable filebeat module
  shell: 'filebeat modules enable system'

- name: Start filebeat service
  service:
   name: filebeat
   state: started
   enabled: yes

#Stoping Nginx service
- name: Stop Nginx service for next installation
  service:
   name: nginx
   state: stopped

#Nagios
- name: Downloading required Packages
  apt:
   name:
    - apache2
    - libapache2-mod-php
    - build-essential
    - libgd-dev
    - unzip
   state: latest
   update_cache: yes

- name: Creating nagios group1
  group:
   name: nagios
   state: present

- name: Creating nagios group2
  group:
   name: nagcmd
   state: present

- name: Creating Nagios User
  user:
   name: nagios
   shell: /bin/bash
   comment: nagios user
   group: nagios
   password: '{{ usernagios }}'

- name: External Command configuration for nagios
  user:
   name: nagios
   group: nagcmd
   append: yes

- name: External Command configuration for www-data
  user:
   name: www-data
   group: nagcmd
   append: yes

- name: Create downloads directory
  file:
   path: /downloads
   state: directory
   owner: nobody
   group: nogroup

- name: Downloading Nagios
  get_url:
   url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
   dest: /downloads

- name: Downloading Plugins
  get_url:
   url: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
   dest: /downloads

- name: Extract Nagios Core
  unarchive:
   src: /downloads/nagios-4.2.1.tar.gz
   dest: /downloads
   remote_src: yes

- name: Configuring Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/
  args:
   chdir: /downloads/nagios-4.2.1

- name: Compiling Nagios Core
  make:
   chdir: /downloads/nagios-4.2.1
   target: all

- name: Downloading Binaries
  make:
   chdir: /downloads/nagios-4.2.1
   target: install

- name: Downloading init script
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-init

- name: Downloading sample config files
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-config

- name: Downloading set permissions
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-commandmode

- name: Downloading Nagios web interface
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-webconf

- name: Create nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ adminnagios }}'

- name: Restart Apache
  service:
   name: apache2
   state: reloaded

- name: Extract Nagios Plugins
  unarchive:
   src: /downloads/nagios-plugins-2.3.3.tar.gz
   dest: /downloads
   remote_src: yes

- name: Configure Plugin Script
  shell: ./configure --with-nagios-user=nagios --with-nagios-group=nagios
  args:
   chdir: /downloads/nagios-plugins-2.3.3

- name: Compile Plugins PART1
  make:
   chdir: /downloads/nagios-plugins-2.3.3
  become: yes

- name: Compiles Plugins PART2
  make:
   chdir: /downloads/nagios-plugins-2.3.3
   target: install
  become: yes


#Stop apache
- name: Stoping Apache for next installation
  service:
   name: apache2
   state: stopped

#Grafana
- name: Generating the Grafana public GPG key into APT
  apt_key:
   url: https://packages.grafana.com/gpg.key
   state: present

- name: Making Grafana source list accessible
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Downloading Grafana
  apt:
   name: grafana
   update_cache: yes

- name: Start Grafana server
  service:
   name: grafana-server
   state: started
   enabled: yes

- name: Configure Nginx
  copy:
   src: others/grafana
   dest: /etc/nginx/sites-available

- name: Reload Nginx
  systemd:
   name: nginx
   state: reloaded

- name: Disable Registration
  replace:
   path: /etc/grafana/grafana.ini
   regexp: ";allow_sign_up = true"
   replace: "allow_sign_up = false"
   after: "# disable user signup / registration"

- name: Disable Anonymous Access
  replace:
   path: /etc/grafana/grafana.ini
   regexp: ";enabled = false"
   replace: "enabled = false"
   after: "# enable anonymous access"

- name: Restart Grafana
  systemd:
   name: grafana-server
   state: restarted

#Prometheus
- name: Creating Directory PART1
  file:
   path: /etc/prometheus
   state: directory
   group: nogroup
   owner: nobody
   mode: '0755'

- name: Creating Directory PART2
  file:
   path: /var/lib/prometheus
   state: directory
   group: nogroup
   owner: nobody
   mode: '0755'

- name: Downloading Prometheus
  get_url:
   url:  https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
   dest: /downloads

- name: Extract prometheus file
  unarchive:
   src: /downloads/prometheus-2.0.0.linux-amd64.tar.gz
   dest: /downloads
   remote_src: True

- name: Copy Prometheus to local
  copy:
   src: /downloads/prometheus-2.0.0.linux-amd64/prometheus
   dest: /usr/local/bin/
   remote_src: True

- name: Copy Prometool to local
  copy:
   src: /downloads/prometheus-2.0.0.linux-amd64/promtool
   dest: /usr/local/bin/
   remote_src: True

- name: Make prometheus executable
  file:
   path: /usr/local/bin/prometheus
   mode: u+x,g+x,o+x

- name: Make prometool executable
  file:
   path: /usr/local/bin/promtool
   mode: u+x,g+x,o+x

- name: Copying consoles
  shell: 'cp -r /downloads/prometheus-2.0.0.linux-amd64/consoles /etc/prometheus'

- name: Copying console library
  shell: 'cp -r /downloads/prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus'

- name: Make Prometheus configuration
  copy:
   src: others/prometheusconfig
   dest: /etc/prometheus/prometheus.yml

- name: File for systemd service
  copy:
   src: others/prometheusservice
   dest: /etc/systemd/system/prometheus.service

- name: Reload systemd services
  systemd:
   daemon_reload: yes

- name: Start Prometheus
  service:
   name: prometheus
   enabled: yes
   state: started
