---
- name: Getting the influxdb public GPG key and turn into APT
  apt_key:
   url: https://repos.influxdata.com/influxdb.key
   state: present

- name: Creating a source list for influxdb
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
    state: present

- name: Packages Updating 
  apt:
   update_cache: yes

- name: Establishing the influxdb
  apt:
   name: influxdb
   update_cache: yes

- name: Starting influxdb
  service:
   name: influxdb
   state: started
   enabled: yes


- name: Firewall activation
  ufw:
   state: enabled

- name: Starting the port
  ufw:
   rule: allow
   proto: tcp
   port: '8086'
# tasks file for roles/rolesinfluxdb