---
- name: Removing the container of elastic search
  docker_container:
   name: elasticsearch
   state: absent

- name: Generate a network named elasticnet
  docker_network:
   name: elasticnet

- name: Establish and generate a elastic search container
  docker_container:
   name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
   networks:
    - name: elasticnet
   networks_cli_compatible: yes
   env:
    discovery.type: "single-node"
   ports:
      - 9200:9200
      - 9300:9300

- name: Generate a container for kibana
  docker_container:
   name: kibana
   image: docker.elastic.co/kibana/kibana:7.10.1
   networks: 
    - name: elasticnet
   networks_cli_compatible: yes
   env:
    discovery.type: "single-node"
   ports:
      - 5601:5601
# tasks file for roles/kibana