---
# tasks file for roles/rolescentos
#Elasticsearch
- name: Downloading Java
  yum:
   name: java-11-openjdk-devel
   state: latest
   update_cache: yes

- name: Generating ELK public GPG key
  rpm_key:
   key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   state: present

- name: Creating ELK source list
  copy:
   src: needed_files/elasticsearch.repo
   dest: /etc/yum.repos.d/

- name: Downloading Elasticsearch
  yum:
   name: elasticsearch
   state: latest
   update_cache: yes

- name: Configure cluster name
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name: my-application'
   replace: 'cluster.name: my-application'

- name: Configure node
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#node.name: node-1'
   replace: 'node.name: node-1'

- name: Configure network host
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#network.host: 192.168.0.1'
   replace: '{{ elasticnetwork }}'

- name: Configure port
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#http.port: 9200'
   replace: 'http.port: 9200'

- name: Update service startup timeout
  lineinfile:
   path: /etc/systemd/system/elasticsearch.service.d/startup-timeout.conf
   line: '{{ elastictimeout }}'
   create: yes
  register: timeout

- name: Restart systemd manager
  systemd:
   daemon_reload: yes
  when: timeout.changed

- name: Starting Elasticsearch Service
  service:
   name: elasticsearch
   enabled: yes
   state: started

#Kibana
- name: Downloading Dependency
  yum:
   name: nginx
   update_cache: yes

- name: Downloading Kibana
  yum:
   name: kibana
   update_cache: yes

- name: Start kibana
  service:
   name: kibana
   state: started
   enabled: yes

- name: Installing pip
  yum:
   name: python3-pip
   state: latest
   update_cache: yes

- name: Making sure htpasswd module is present
  pip:
   name: passlib
   state: latest

- name: Create Admin User
  htpasswd:
   path: /etc/nginx/htpasswd.users
   name: kibanaadmin
   password: '{{ kibanapass }}'

- name: Create Nginx Virtual Host Configuration file
  copy:
   src: others/kibana
   dest: /etc/nginx/conf.d

- name: Restart nginx
  service:
   name: nginx
   state: restarted

#Logstash
- name: Downloading Logstash
  yum:
   name: logstash
   update_cache: yes

- name: Downloading Filebeat
  yum:
   name: filebeat
   update_cache: yes

- name: Generating the 1st configuration file
  copy:
   src: others/02-beats-input.conf
   dest: /etc/logstash/conf.d

- name: Generating the 2nd configuration file
  copy:
   src: others/10-syslog-filter.conf
   dest: /etc/logstash/conf.d

- name: Generating the 3rd configuration file
  copy:
   src: others/30-elasticsearch-output.conf
   dest:  /etc/logstash/conf.d

- name: Start Logstash
  service:
   name: logstash
   state: started
   enabled:

- name: Editing Filebeat Configuration PART1
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: 'output.elasticsearch:'
   replace: '#output.elasticsearch:'

- name: Editing Filebeat Configuration PART2
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: 'hosts:'
   replace: '#hosts:'
   after: 'output.elasticsearch:'
   before: 'Protocol - either'

- name: Editing Filebeat Configuration PART3
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: '#output.logstash:'
   replace: 'output.logstash:'

- name: Editing Filebeat Configuration PART4
  replace:
   path: /etc/filebeat/filebeat.yml
   regexp: '#hosts:'
   replace: 'hosts:'
   after: 'output.logstash:'
   before: ' Optional SSL.'

- name: Enable filebeat module
  shell: 'filebeat modules enable system'

- name: Start filebeat
  service:
   name: filebeat
   state: started
   enabled: yes

#Stoping Nginx service
- name: Stop Nginx service for next installation
  service:
   name: nginx
   state: stopped

#Nagios
- name: Downloading required Packages
  yum:
   name:
    - httpd
    - gcc
    - glibc
    - glibc-common
    - gd-devel
    - perl
    - postfix
    - unzip
   state: latest
   update_cache: yes

- name: Starting httpd service
  service:
   name: httpd
   state: started

- name: Create nagios group
  group:
   name: nagios
   state: present

- name: Create nagios group
  group:
   name: nagcmd
   state: present

- name: Create Nagios User
  user:
   name: nagios
   shell: /bin/bash
   comment: nagios user
   group: nagios
   password: '{{ usernagios }}'

- name: Make httpd append to nagios group
  user:
   name: apache
   groups: nagios
   append: yes

- name: AExternal Command configuration for nagios
  user:
   name: nagios
   group: nagcmd
   append: yes

- name: External Command configuration for www-data
  user:
   name: www-data
   group: nagcmd
   append: yes

- name: Create downloads directory
  file:
   path: /downloads
   state: directory

- name: Downloading Nagios package
  get_url:
   url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
   dest: /downloads

- name: Extract Nagios Core
  unarchive:
   src: /downloads/nagios-4.2.1.tar.gz
   dest: /downloads
   remote_src: yes

- name: Creating Virtual Host Directory
  file:
   path: /etc/httpd/conf.d
   state: directory

- name: Configuring Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
   chdir: /downloads/nagios-4.2.1

- name: Compiling Nagios Core
  make:
   chdir: /downloads/nagios-4.2.1
   target: all

- name: Downloading Binaries
  make:
   chdir: /downloads/nagios-4.2.1
   target: install

- name: Downloading init script
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-init

- name: Downloading sample config files
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-config

- name: Downloading set permissions
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-commandmode

- name: Downloading Nagios web interface
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-webconf

- name: Create nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ adminnagios }}'

- name: Restarting Apache
  service:
   name: httpd
   state: reloaded

#Stop apache
- name: Stoping Apache for next installation
  service:
   name: httpd
   state: stopped

#Grafana
- name:  Generating the Grafana public GPG key into APT
  rpm_key:
   key: https://packages.grafana.com/gpg.key
   state: present

- name:  Making Grafana source list accessible
  copy:
   src: needed_files/grafana.repo
   dest: /etc/yum.repos.d/

- name: Downloading Grafana
  yum:
   name: grafana
   state: latest
   update_cache: yes

- name: Start Grafana server
  service:
   name: grafana-server
   state: started
   enabled: yes

- name: Configure Nginx
  copy:
   src: others/grafana
   dest: /etc/nginx/sites-available

- name: Reload Nginx
  systemd:
   name: nginx
   state: reloaded

- name: Disable Registration
  replace:
   path: /etc/grafana/grafana.ini
   regexp: ";allow_sign_up = true"
   replace: "allow_sign_up = false"
   after: "# disable user signup / registration"

- name: Disable Anonymous Access
  replace:
   path: /etc/grafana/grafana.ini
   regexp: ";enabled = false"
   replace: "enabled = false"
   after: "# enable anonymous access"

- name: Restart Grafana
  systemd:
   name: grafana-server
   state: restarted

#Prometheus
- name: Creating Directory PART1
  file:
   path: /etc/prometheus
   state: directory
   mode: '0755'

- name: Creating Directory PART2
  file:
   path: /var/lib/prometheus
   state: directory
   mode: '0755'

- name: Downloading Prometheus
  get_url:
   url:  https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
   dest: /downloads

- name: Extract prometheus file
  unarchive:
   src: /downloads/prometheus-2.0.0.linux-amd64.tar.gz
   dest: /downloads
   remote_src: True

- name: Copying Prometheus to local
  copy:
   src: /downloads/prometheus-2.0.0.linux-amd64/prometheus
   dest: /usr/local/bin/
   remote_src: True

- name: Copying Prometool to local
  copy:
   src: /downloads/prometheus-2.0.0.linux-amd64/promtool
   dest: /usr/local/bin/
   remote_src: True

- name: Make prometheus executable
  file:
   path: /usr/local/bin/prometheus
   mode: u+x,g+x,o+x

- name: Make prometool executable
  file:
   path: /usr/local/bin/promtool
   mode: u+x,g+x,o+x

- name: Copying consoles
  shell: 'cp -r /downloads/prometheus-2.0.0.linux-amd64/consoles /etc/prometheus'

- name: Copying console library
  shell: 'cp -r /downloads/prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus'

- name: Make Prometheus configuration
  copy:
   src: others/prometheusconfig
   dest: /etc/prometheus/prometheus.yml

- name: File for systemd service
  copy:
   src: others/prometheusservice
   dest: /etc/systemd/system/prometheus.service

- name: Reload systemd services
  systemd:
   daemon_reload: yes

- name: Start Prometheus
  service:
   name: prometheus
   enabled: yes
   state: started


