---
- name: Establishing a Java
  apt:
   name: openjdk-11-jdk

- name: Getting Elastic search GPG key and turn to APT
  apt_key:
   url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   state: present

- name: Creating a list for the source of Elastic Search
  lineinfile: 
   path: /etc/apt/sources.list.d/elastic-7.x.list
   line: '{{ elasticsource }}'
   create: yes

- name: Updating the packages
  apt:
   update_cache: yes

- name: Establishing the Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

- name: Setup for clustername in elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name: my-application'
   replace: 'cluster.name: my-application'

- name: Setup for node in elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#node.name: node-1'
   replace: 'node.name: node-1'

- name: Setup a network host for elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#network.host: 192.168.0.1'
   replace: '{{ elasticnetwork }}'

- name: Setup the port for elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#http.port: 9200'
   replace: 'http.port: 9200'

- name: Service startup timeout
  lineinfile:
   path: /etc/systemd/system/elasticsearch.service.d/startup-timeout.conf
   line: '{{ elastictimeout }}'
   create: yes
  register: timeout

- name: Systemd manager restart
  systemd:
   daemon_reload: yes
  when: timeout.changed

- name: Starting the elasticsearch Service
  service:
   name: elasticsearch
   enabled: yes
   state: started
# tasks file for roles/roleselastic

