---
# tasks file for roles/clone_debian
- name: Installation of git into debian
  apt:
   name: git
   state: latest

- name: Cloning the branch og prelim to debian
  git:
    repo: '{{ prelim_exam }}'
    dest: ./prelim-exam
    version: prelim-exam
